export const  userEndPoints = {
  signUp : "/api/register",
  signIn : "/api/login",
  verifyOtp : "/api/verifyOtp",
  forgotPassword : "/api/forgotPassword",
  logout : "/api/logout",
  getToken : "/api/getToken",
  resendOtp : "/api/resendOtp",
  googleAuth: "/api/googleLogin",
  resetPassword: "/api/resetPassword",
  getRentProperty: "/api/getRentProperty",
  getSaleProperty : "/api/getSaleProperty",
  updateUser : "/api/updateUser",
  getPremium : "/api/getPremium",
  updatePremium : "/api/updatePremium",
  productDetail : "/api/productDetail",
  googleRegister : '/api/googleRegister',
  sendOwnerDetail : "/api/sendOwnerDetail",
  getUser : "/api/getUser",
  setBrowserToken:"/api/setBrowserToken",
  whishlist : "/api/whishlist"
}